config/routes.rb
Rails.application.routes.draw do
  get '/help',to:'static_pages#help'
  get '/about',to:'static_pages#about'
  get '/contact',to:'static_pages#contact'
  get '/signup',to: 'users#new'
  get '/login',to:'sessions#new'
  post '/login',to:'sessions#create'
  delete '/logout',to:'sessions#destroy'
  resources :users
  resources :account_activations, only:[:edit]
  resources :micropost, only:[:create,:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'static_pages#home'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope ->{order(created_at: :desc)}
  validates :user_id,presence: true
  validates :content,presence: true, length:{ maximum: 140}
end

app/models/user.rb
class User < ApplicationRecord
	has_many :microposts,dependent: :destroy
	attr_accessor :remember_token,:activation_token
	before_save :downcase_email 
	before_create :create_activation_digest

	before_save {self.email = email.downcase}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :name,presence:true,length:{maximum:50}
	validates :email,presence:true,length:{maximum:255},
																	format:{with:VALID_EMAIL_REGEX},
																	uniqueness: true
  # validates :password,presence:true,length:{minimum:6}
 	has_secure_password

 	def User.digest(string)
		cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
		BCrypt::Engine.cost
		BCrypt::Password.create(string, cost: cost)
	end

 	def self.new_token
 		SecureRandom.urlsafe_base64
 	end

 	def remember 
 		self.remember_token = User.new_token 
 		update_attribute(:remember_digest,User.digest(remember_token))
 	end

	def authenticated?(attribute, token)
		digest = send("#{attribute}_digest")
		return false if digest.nil?
		BCrypt::Password.new(digest).is_password?(token)
	end

 	def forget 
 		update_attribute(:remember_digest,nil)
 	end

 	def activate
 		update_columns(activated: FILL_IN, activated_at: FILL_IN)
	end

	def send_activation_email
		UserMailer.account_activation(self).deliver_now
	end

 	private
 		def downcase_email
 			self.email = email.downcase
 		end

 		def create_activation_digest
 			self.activation_token = User.new_token
 			self.activation_digest = User.digest(activation_token)
 		end
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
	def edit
		user = User.find_by(email: params[:email])
		if user && user.activated? && user.authenticated?(:activation,params[:id])
			# user.update_attribute(:activated, true)
			# user.update_attribute(:activated_at, Time.zone.now)
			user.activate
			log_in user
			flash[:success] = "Account activated!"
			redirect_to user
		else
			flash[:danger] = "Invalid activation link"
			redirect_to root_url
		end
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	include SessionsHelper

	private
		def logged_in_user
			unless logged_in?
				store_location
				flash[:danger] = '请登录'
				redirect_to login_url
			end
		end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :logged_in_user only: [:create,:destroy]

	def create
		@micropost = current_user.microposts.build(micropost_params)
		if @micropost.save
			flash[:success] = '保存成功'
			redirect_to root_url
		else
			render 'static_pages/home'
		end
	end

	def destroy
	end

	private
		def micropost_params
			params.require(:micropost).permit(:content)
		end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&&user.authenticate(params[:session][:password])
      if user.activated?
        log_in user
        params[:session][:remember_my]==='1'? remember(user) : forget(user)
        redirect_back_or user
      else
        message = "Account not activated. "
        message += "Check your email for the activation link."
        flash[:warning] = message
        redirect_to root_url
      end
    else
      flash.now[:danger] = '密码错误'
      render 'new'
    end
  end

  def destroy
    log_out if loggin?
    redirect_to root_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @micropost = current_user.microposts.build 
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user,only:[:index,:edit,:update,:destroy]
  before_action :correct_user,only:[:edit,:update]

  def index
    @users = User.all
    # @users = User.where(activated: FILL_IN).paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create  
    @user = User.new(user_detail)
    if @user.save
      # log_in @user
      # flash[:success] = 'let go'
      # redirect_to @user
      
      @user.send_activation_email
      flash[:info] = "Please check your email to activate your account."
      redirect_to root_url
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_detail)
      flash[:success] = '修改成功'
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = ' 删除成功'
    redirect_to users.url
  end

  private
    def user_detail
      params.require(:user).permit(:name,:email,:password,:password_confirmation)
    end
    
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Ruby on Rails Tutorial Sample App"
		if page_title.empty?
			base_title
		else
			page_title + '|' + base_title
		end
	end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def current_user
		if user_id = session[:user_id]
		  @current_user ||= User.find_by(id: session[:user_id])			
		elsif user_id = cookies.signed[:user_id]
			user = User.find_by(id:cookies.signed[:user_id])
			if user&&user.authenticated?(:remember,cookies[:remember_token])
				log_in user
				@current_user = user
			end
		end
	end

	def loggin?
		!current_user.nil?
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def current_user?(user)
		user && user == current_user
	end

	def redirect_back_or(default)
		redirect_to session[:forwarding_url] || default
		session.delete(:forwarding_url)
	end

	def store_location
		session[:forwarding_url] = request.original_url  if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user,options = {size:80})
		size = options[:size]
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url,alt: user.name,class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		The <a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
		by <a href="https://www.michaelhartl.com/">Michael Hartl</a>
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><%= link_to "news", new_user_path%></li>
		</ul>
	</nav>
</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title)%></title>

    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
      <%= link_to "sample app", root_path, id: "logo" %>
        <nav>
        <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "Help", help_path %></li>
          <% if loggin?%>
            <li><%= link_to "Users", users_path %></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
            <li><%= link_to "Profile", current_user %></li>
            <li><%= link_to "Settings", edit_user_path(current_user) %></li>
            <li class="divider"></li>
            <li>
              <%= link_to "Log out", logout_path, method: :delete %>
            </li>
            </ul>
          <% else%>
            <li><%= link_to "Log in", login_path %></li>
          <% end%>
        </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer'%>
      <%= debug(params) if Rails.env.development?%>
    </div>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
	<%= link_to '姓名：', micropost.user %>
	<span class="user"><%= link_to micropost.user.name, micropost.user %></span>
	<span class="content"><%= micropost.content %></span>
	<span class="timestamp">
	Posted <%= time_ago_in_words(micropost.created_at) %> ago.
	</span>
</li>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
<div id="error_explanation">
	<div class="alert alert-danger">
		The form contains <%= pluralize(object.errors.count, "error") %>.
	</div>
	<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
	</ul>
</div>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to 111, current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>Sample App</h1>
<p>
This is the home page for the
<a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
sample application.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title,'Contact')%>
<h1>111</h1>
<p>
Contact the Ruby on Rails Tutorial about the sample app at the
<a href="https://www.railstutorial.org/contact">contact page</a>.
</p>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% if loggin? %>
	<div class="row">
		<aside class="col-md-4">
			<section class="user_info">
				<%= render 'shared/user_info' %>
			</section>
			<section class="micropost_form">
				<%= render 'shared/micropost_form' %>
			</section>
		</aside>
	</div>
<% else %>

<div class="center jumbotron">
		<h1>Welcome to the Sample App</h1>
		<h2>This is the home page for the
				<a href="https://www.railstutorial.org/">Ruby on Rails Tutorial</a>
				sample application.
		</h2>
		<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
    
<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200"),
"https://rubyonrails.org/" %>
<% end%>

app/views/users/_user.html.erb
<li>
	<%= link_to user.name,user%>
	<% if current_user.admin? && !current_user?(user) %>
	|<%= link_to 'delete',user,method: :delete,data:{confirm:'que ding'}%>
	<% end%>
</li>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_with(model: @user, local: true) do |f| %>
		<%= render 'shared/error_messages' object: f.object%>
		<%= f.label :name %>
		<%= f.text_field :name, class: 'form-control' %>
		<%= f.label :email %>
		<%= f.email_field :email, class: 'form-control' %>
		<%= f.label :password %>
		<%= f.password_field :password, class: 'form-control' %>
		<%= f.label :password_confirmation, "Confirmation" %>
		<%= f.password_field :password_confirmation, class: 'form-control' %>
		<%= f.submit "Save changes", class: "btn btn-primary" %>
		<% end %>
		<div class="gravatar_edit">
			<%= gravatar_for @user %>
			<a href="https://gravatar.com/emails" target="_blank">change</a>
		</div>
	</div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>


<ul class="users">
		<%= render @users%>
</ul>
<%= will_paginate%>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>
<div class="row">
	<div class="col-md-6 col-md-offset-3">
		<%= form_with(model:@user,local:true) do |f|%>
			<%= render 'shared/error_messages',object:f.object%>
			<%= f.label :name%>
			<%= f.text_field :name,class: 'form-control'%>

			<%= f.label :email%>
			<%= f.email_field :email,class: 'form-control'%>

			<%= f.label :password%>
			<%= f.password_field :password,class: 'form-control'%>

			<%= f.label :password_confirmation, "Confirmation"%>
			<%= f.password_field :password_confirmation,class: 'form-control'%>

			<%= f.submit "gogogogo",class:"btn btn-primary"%>
		<% end%>
	</div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
	<aside class="col-md-4">
		<section class="user_info">
			<h1>

				<%= @user.name %>
			</h1>
		</section>
	</aside>
	<div class="col-md-8">
		<% if @user.microposts.any? %>
			<h3>Microposts (<%= @user.microposts.count %>)</h3>
			<ol class="microposts">
				<%= render @microposts %>
			</ol>
			<%= will_paginate @microposts %>
		<% end %>
	</div>
</div>